// GENERATED by scripts/prep-posters.mjs. Edit the manifest there, not this file.
//
// Every value here was printed on a poster. Nothing is inferred. A product with no
// `sizes` genuinely has no size printed on its poster, and the page shows nothing
// rather than a guess.

import type { PatternId } from './patterns'

export type ProductKind = 'jali' | 'brick' | 'block'

export type Product = {
  slug: string
  /** exactly as printed on the poster, misspellings preserved */
  name: string
  kind: ProductKind
  sizes?: string[]
  weightKg?: number
  /** set only for the patterns modelled in 3D */
  pattern?: PatternId
  poster: string
  thumb: string
}

export const PRODUCTS: Product[] = [
  {
    slug: 'arrow',
    name: 'Arrow',
    kind: 'jali',
    sizes: ['8 x 8 in'],
    pattern: 'arrow',
    poster: '/posters/arrow.webp',
    thumb: '/posters/arrow-thumb.webp',
  },
  {
    slug: 'circle',
    name: 'Circle',
    kind: 'jali',
    pattern: 'circle',
    poster: '/posters/circle.webp',
    thumb: '/posters/circle-thumb.webp',
  },
  {
    slug: 'camp',
    name: 'Camp',
    kind: 'jali',
    poster: '/posters/camp.webp',
    thumb: '/posters/camp-thumb.webp',
  },
  {
    slug: 'amber',
    name: 'Amber',
    kind: 'jali',
    sizes: ['8 x 8 in'],
    weightKg: 2.5,
    pattern: 'amber',
    poster: '/posters/amber.webp',
    thumb: '/posters/amber-thumb.webp',
  },
  {
    slug: 'cross',
    name: 'Cross',
    kind: 'jali',
    pattern: 'cross',
    poster: '/posters/cross.webp',
    thumb: '/posters/cross-thumb.webp',
  },
  {
    slug: 'ludo',
    name: 'Ludo',
    kind: 'jali',
    poster: '/posters/ludo.webp',
    thumb: '/posters/ludo-thumb.webp',
  },
  {
    slug: 'petal',
    name: 'Petal',
    kind: 'jali',
    poster: '/posters/petal.webp',
    thumb: '/posters/petal-thumb.webp',
  },
  {
    slug: 'daimond',
    name: 'Daimond',
    kind: 'jali',
    poster: '/posters/daimond.webp',
    thumb: '/posters/daimond-thumb.webp',
  },
  {
    slug: 'pearl',
    name: 'Pearl',
    kind: 'jali',
    poster: '/posters/pearl.webp',
    thumb: '/posters/pearl-thumb.webp',
  },
  {
    slug: 'opel',
    name: 'Opel',
    kind: 'jali',
    poster: '/posters/opel.webp',
    thumb: '/posters/opel-thumb.webp',
  },
  {
    slug: 'lotus',
    name: 'Lotus',
    kind: 'jali',
    poster: '/posters/lotus.webp',
    thumb: '/posters/lotus-thumb.webp',
  },
  {
    slug: 'slice',
    name: 'Slice',
    kind: 'jali',
    poster: '/posters/slice.webp',
    thumb: '/posters/slice-thumb.webp',
  },
  {
    slug: 'star',
    name: 'Star',
    kind: 'jali',
    pattern: 'star',
    poster: '/posters/star.webp',
    thumb: '/posters/star-thumb.webp',
  },
  {
    slug: 'tv',
    name: 'Tv',
    kind: 'jali',
    poster: '/posters/tv.webp',
    thumb: '/posters/tv-thumb.webp',
  },
  {
    slug: 'zebra',
    name: 'Zebra',
    kind: 'jali',
    pattern: 'zebra',
    poster: '/posters/zebra.webp',
    thumb: '/posters/zebra-thumb.webp',
  },
  {
    slug: 'swastik',
    name: 'Swastik',
    kind: 'jali',
    poster: '/posters/swastik.webp',
    thumb: '/posters/swastik-thumb.webp',
  },
  {
    slug: 'w',
    name: 'W',
    kind: 'jali',
    sizes: ['12 x 8 in', '10 x 7 in', '8 x 8 in'],
    poster: '/posters/w.webp',
    thumb: '/posters/w-thumb.webp',
  },
  {
    slug: 'topaz',
    name: 'Topaz',
    kind: 'jali',
    poster: '/posters/topaz.webp',
    thumb: '/posters/topaz-thumb.webp',
  },
  {
    slug: 'lilly',
    name: 'Lilly',
    kind: 'jali',
    poster: '/posters/lilly.webp',
    thumb: '/posters/lilly-thumb.webp',
  },
  {
    slug: 'leaf',
    name: 'Leaf',
    kind: 'jali',
    pattern: 'leaf',
    poster: '/posters/leaf.webp',
    thumb: '/posters/leaf-thumb.webp',
  },
  {
    slug: 'capsul',
    name: 'Capsul',
    kind: 'brick',
    poster: '/posters/capsul.webp',
    thumb: '/posters/capsul-thumb.webp',
  },
  {
    slug: 'two-hole-square-bricks',
    name: '2 Hole Square Bricks',
    kind: 'brick',
    poster: '/posters/two-hole-square-bricks.webp',
    thumb: '/posters/two-hole-square-bricks-thumb.webp',
  },
  {
    slug: 'ten-hole-bricks',
    name: '10 Hole Bricks',
    kind: 'brick',
    poster: '/posters/ten-hole-bricks.webp',
    thumb: '/posters/ten-hole-bricks-thumb.webp',
  },
  {
    slug: 'omega-jali',
    name: 'Omega Jali',
    kind: 'block',
    poster: '/posters/omega-jali.webp',
    thumb: '/posters/omega-jali-thumb.webp',
  },
  {
    slug: 'three-hole-bricks',
    name: '3 Hole Bricks',
    kind: 'brick',
    poster: '/posters/three-hole-bricks.webp',
    thumb: '/posters/three-hole-bricks-thumb.webp',
  },
  {
    slug: 'greek-bricks',
    name: 'Greek Bricks',
    kind: 'jali',
    poster: '/posters/greek-bricks.webp',
    thumb: '/posters/greek-bricks-thumb.webp',
  },
  {
    slug: 'stepper-jali',
    name: 'Stepper Jali',
    kind: 'jali',
    poster: '/posters/stepper-jali.webp',
    thumb: '/posters/stepper-jali-thumb.webp',
  },
  {
    slug: 'window',
    name: 'Window',
    kind: 'jali',
    pattern: 'window',
    poster: '/posters/window.webp',
    thumb: '/posters/window-thumb.webp',
  },
]

export const KIND_LABEL: Record<ProductKind, string> = {
  jali: 'Jali screens',
  brick: 'Perforated bricks',
  block: 'Special blocks',
}
